### ISSUE TITLE
Question - connecting to legacy ssh then using sshFs.createReadStream(ssh, path) errors but works fine on non-legacy ssh server

### ISSUE THREAD

**Issue by lasergoat** [wdavidw/node-ssh2-fs#4]
I've got this code:
```ES6

  new Promise((resolve, reject) => {
    const conn = new ssh2.Client();
    let params = {
      host: process.env.SFTP_HOST,
      port: process.env.SFTP_PORT,
      username: process.env.SFTP_USER,
      password: process.env.SFTP_PASS,
      algorithms: {
        kex: ["diffie-hellman-group1-sha1"],
        cipher: ["aes128-cbc"],
        hmac: ["hmac-sha1"],
        serverHostKey: ["ssh-rsa"],
        compress: ["none"]
      }
    };

    conn.on('ready', function() {
      debug('SFTP Client :: ready');
      resolve(conn);
    })
    .on('error', (err) => {
      console.error(err);
      reject(err);
    })
    .connect(params);
```
That works just fine for this legacy server. Then I do a readdir and get a list of files. This part also works. BUT then I do:

```ES6
          debug(`Downloading File As: ${name}`);
          return new Promise((resolve, reject) => {
            sshFs.createReadStream(
              ssh,
              path.join(REMOTE_DIRECTORY, file),
              (err, readStream) => {
                if (err) {
                  return reject(err);
                }

                resolve(readStream);
              }
            )
          })
```

**And that gives me my error**: `Unable to start subsystem: sftp`

The issue is that this code works just fine on non-legacy ftp systems - but as you can see I have the older algorithms supplied. That enables it to connect and readdir on this legacy server but the `createReadStream` errors. Is it possible that more configuration is needed for the createReadStream?

Thanks!!

**Comment by lasergoat** [comment]
Just got a better error:

```
{ Error: Failed to read binary packet data!
    at onDISCONNECT (/Users/u/project/node_modules/ssh2-streams/lib/ssh.js:2197:15)
    at SSH2Stream.<anonymous> (/Users/u/project/node_modules/ssh2-streams/lib/ssh.js:203:5)
    at emitMany (events.js:127:13)
    at SSH2Stream.emit (events.js:201:7)
    at parsePacket (/Users/u/project/node_modules/ssh2-streams/lib/ssh.js:3742:10)
    at SSH2Stream._transform (/Users/u/project/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/u/project/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12) code: 2, level: 'protocol' }

Error: Unable to start subsystem: sftp +246ms


```

**Comment by wdavidw** [comment]
This isnt an issue with ssh2-fs but directly with the [ssh2](https://github.com/mscdex/ssh2) package. We only provide an interface compliant with the native fs module but the sftp instance is in ssh2

**Comment by lasergoat** [comment]
I'll should probably open the issue on ssh2 then?

**Comment by wdavidw** [comment]
This is my understanding.
